tap "acrogenesis/macchanger"
tap "an5ible/brew"
tap "hettysoft/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "lotyp/formulae"
tap "shopify/shopify"
tap "xwmx/taps"
brew "ansible"
brew "atuin"
brew "aws-sam-cli"
brew "awscli"
brew "bat"
brew "broot"
brew "chezmoi"
brew "difftastic"
brew "dust"
brew "exa"
brew "fzf"
brew "gnupg"
brew "gopass"
brew "gopass-jsonapi"
brew "macos-trash"
brew "mas"
brew "micro"
brew "mitmproxy"
brew "node"
brew "pinentry-mac"
brew "poetry"
brew "postgresql@13"
brew "starship"
brew "zoxide"
brew "acrogenesis/macchanger/macchanger"
brew "hettysoft/tap/hetty"
brew "lotyp/formulae/dockutil", link: false
brew "xwmx/taps/hosts"
cask "airtable"
cask "background-music"
cask "bitwarden"
cask "dbeaver-community"
cask "devutils"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "keyclu"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-word"
cask "mudlet"
cask "obsidian"
cask "office-serializer"
cask "pgadmin4"
cask "rectangle"
cask "redisinsight"
cask "telegram-desktop"
cask "ubersicht"
cask "visual-studio-code"
cask "warp"
mas "2FAS - Two Factor Authentication Extension", id: 6443941139
mas "Bitwarden", id: 1352778147
mas "Boop", id: 1518425043
mas "FlagSwitcher", id: 1157313107
mas "Moom", id: 419330170
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Xcode", id: 497799835
vscode "charliermarsh.ruff"
vscode "donjayamanne.githistory"
vscode "humao.rest-client"
vscode "mhutchie.git-graph"
vscode "ms-python.black-formatter"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "qwtel.sqlite-viewer"
vscode "ZainChen.json"
