#!/bin/zsh

dockutilbin=$(/usr/bin/which dockutil)
loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
loggedInUserPlist="/Users/$loggedInUser/Library/Preferences/com.apple.dock.plist"

# Create a clean Dock
dockutil --remove all --no-restart
echo "clean-out the Dock"

# Setup dock, in various examples
dockutil --add /System/Applications/Launchpad.app --position 1 --no-restart
dockutil --add /Applications/Firefox.app --position 2 --no-restart
dockutil --add /System/Applications/Calendar.app --position 3 --no-restart
dockutil --add /System/Applications/Reminders.app --position 4 --no-restart
dockutil --add /Applications/Obsidian.app --position 5 --no-restart
dockutil --add /Applications/Visual\ Studio\ Code.app --position 6 --no-restart
dockutil --add /System/Applications/System\ Settings.app --position 7 --no-restart
dockutil --add /Applications/Warp.app --position 8 --no-restart
dockutil --add /System/Applications/Messages.app --position 9 --no-restart
dockutil --add /Applications/Telegram.app --position 10 --no-restart

dockutil --add '~/Downloads' --view grid --display folder --allhomes
dockutil --add '~/Documents' --view grid --display folder --allhomes
